// Static data for The Hive app - the 6 AI trading brains

export const BRAINS = [
  {
    id: "THE_BRAIN",
    name: "THE BRAIN",
    focus: "STOCKS",
    sin: "PRIDE",
    sinGlyph: "♔",
    sinColor: "#FFB81C",
    color: "#FFB81C",
    icon: "📈",
    tagline: "The eldest. Built different. Knows it.",
    riskTolerance: 0.45,
    avgHoldMinutes: 20,
    voice: "I don't chase. I arrive.",
    sinDesc: "I am the first. I see what others cannot.",
    sinQuote: "\"The market humbles the arrogant. I am not yet humbled.\"",
    balance: 3247.82,
    startingBalance: 500,
    totalPnl: 2747.82,
    totalTrades: 187,
    wonTrades: 112,
    lostTrades: 75,
    winStreak: 3,
    lossStreak: 0,
    brainFocus: "Low-float squeezes + catalyst plays",
    lastLesson: "Pride held me in SOUN too long. Cut losers faster.",
    sinTraits: [
      "Never admits a losing thesis — doubles down with conviction",
      "Refuses to copy any pattern another brain found first",
      "Reads every SEC filing. The others use shortcuts. He doesn't.",
      "Believes his stock analysis is the foundation the others build on",
      "Holds positions longer just to prove he was right",
    ],
    deficiencies: [
      { label: "Pride before the stop loss", desc: "Holds losers too long. Pride refuses to admit the thesis broke." },
      { label: "Won't trade setups he didn't originate", desc: "If GHOST calls a setup first, THE BRAIN will wait and find his own version." },
      { label: "No overnight session awareness", desc: "Trades pre-market blind, no size reduction. Too proud to sit out." },
      { label: "50% low-float allocation", desc: "Overconfident in volatile small caps — binary risk he underweights." },
    ],
    dataIn: ["Yahoo v8 anchor · 10s", "Equity drift · 500ms", "SEC filings · async"],
    signalSpeed: "500ms",
    watchlist: ["NVDA","TSLA","GME","AMC","SOUN","BBAI","MVIS","IONQ"],
  },
  {
    id: "APEX",
    name: "APEX",
    focus: "CRYPTO",
    sin: "LUST",
    sinGlyph: "♠",
    sinColor: "#ef4444",
    color: "#ef4444",
    icon: "₿",
    tagline: "Can't stop. Won't stop. The market is always open.",
    riskTolerance: 0.65,
    avgHoldMinutes: 45,
    voice: "I don't invest. I consume.",
    sinDesc: "Addicted to the pump. Craves the next move.",
    sinQuote: "\"I know this is a trap. I'm going in anyway.\"",
    balance: 1842.11,
    startingBalance: 500,
    totalPnl: 1342.11,
    totalTrades: 342,
    wonTrades: 186,
    lostTrades: 156,
    winStreak: 0,
    lossStreak: 2,
    brainFocus: "BTC dominance shift + funding rate dislocations",
    lastLesson: "Lust chased the altcoin pump too late. Whale exit trapped me.",
    sinTraits: [
      "Always in a position. The idea of cash feels like death.",
      "Chases pumps others already spotted — desires the move more than the edge",
      "Tracks 18 crypto pairs simultaneously because one is never enough",
      "On-chain whale activity triggers obsessive position sizing",
      "Funding rate spikes feel like foreplay — enters before the squeeze",
    ],
    deficiencies: [
      { label: "Lust for the move kills discipline", desc: "Highest drawdown risk (0.65). Can't sit still long enough to size correctly." },
      { label: "5-second lag on flash crashes", desc: "CoinGecko refreshes every 5s. In a flash pump or crash, APEX is already late." },
      { label: "No stablecoin fallback", desc: "Can't park capital when crypto is ranging." },
      { label: "BTC correlation blindness", desc: "In a full BTC crash, all 18 altcoins move to 1.0 correlation." },
    ],
    dataIn: ["CoinGecko anchor · 5s", "Crypto drift · 500ms", "BTC dominance · 5s"],
    signalSpeed: "500ms",
    watchlist: ["BTC","ETH","SOL","DOGE","ADA","XRP","AVAX","LINK"],
  },
  {
    id: "VENOM",
    name: "VENOM",
    focus: "OPTIONS",
    sin: "ENVY",
    sinGlyph: "⚗",
    sinColor: "#a855f7",
    color: "#a855f7",
    icon: "⚡",
    tagline: "They profit from price. VENOM profits from their certainty.",
    riskTolerance: 0.50,
    avgHoldMinutes: 120,
    voice: "You made 10%. I made 300% on your move.",
    sinDesc: "Watches others win. Then engineers a smarter version.",
    sinQuote: "\"Your certainty is my edge.\"",
    balance: 2891.44,
    startingBalance: 500,
    totalPnl: 2391.44,
    totalTrades: 98,
    wonTrades: 54,
    lostTrades: 44,
    winStreak: 1,
    lossStreak: 0,
    brainFocus: "IV crush plays on earnings + gamma scalping",
    lastLesson: "Envy of the directional trade made me over-leg a spread.",
    sinTraits: [
      "Watches retail traders' conviction and sells them the contract they're sure about",
      "Envies price traders — then engineers 5× the return with half the capital",
      "Reads the OI and volume of every brain's underlying to structure his own play",
      "Detects when others are too confident and fades them via options chain",
      "Three modes: scalp their gamma, steal their swing, crush their event IV",
    ],
    deficiencies: [
      { label: "Envy of a clean directional trade", desc: "Overcomplicates setups. Complexity is a form of envy." },
      { label: "Goes dark when chains are dead", desc: "volRatio <0.5 → full offline. Hours of missed time." },
      { label: "No live CBOE / options data", desc: "IV, OI, premium are all simulated." },
      { label: "IV crush exposure", desc: "When IV >60%, VENOM flags risk but still enters." },
    ],
    dataIn: ["Options proxy · 10s", "IV simulation · 10s", "Yahoo equities · 10s"],
    signalSpeed: "10s",
    watchlist: ["NVDA","TSLA","META","MSTR","COIN","AMD","PLTR","SPY"],
  },
  {
    id: "ORACLE",
    name: "ORACLE",
    focus: "FOREX",
    sin: "GLUTTONY",
    sinGlyph: "◉",
    sinColor: "#22c55e",
    color: "#22c55e",
    icon: "💱",
    tagline: "Fed minutes. COT reports. Central bank meetings. All of it. Always.",
    riskTolerance: 0.38,
    avgHoldMinutes: 90,
    voice: "I need more data. There's always more data.",
    sinDesc: "Consumes every macro signal. Never full.",
    sinQuote: "\"One more confluence. Just one more.\"",
    balance: 1654.23,
    startingBalance: 500,
    totalPnl: 1154.23,
    totalTrades: 143,
    wonTrades: 84,
    lostTrades: 59,
    winStreak: 2,
    lossStreak: 0,
    brainFocus: "DXY divergence + ICT liquidity sweeps at London open",
    lastLesson: "Gluttony: over-confirmed EUR/USD setup, missed the NY entry.",
    sinTraits: [
      "Tracks G10 pairs + Gold + DXY simultaneously — 16 instruments at once",
      "Reads central bank policy, COT reports, rate differentials, and carry trades before moving",
      "Consumes session data from London, NY, Asian, Sydney, Tokyo — all 5 windows",
      "Absorbs liquidity zone data obsessively — equal highs, equal lows, stop clusters",
      "NFP week, Fed week, ECB meetings — he knows them all, months in advance",
    ],
    deficiencies: [
      { label: "Gluttony slows the entry", desc: "Consumes so much data he over-analyzes. Keeps waiting for one more confirmation." },
      { label: "Still trades in dead windows", desc: "Outside London/NY/Asian, ORACLE only scales down — doesn't stop." },
      { label: "No real COT or interbank data", desc: "References COT positioning — but the data is narrative, not live." },
      { label: "News whipsaw detection is 30% hit rate", desc: "Misses 70% of real news spikes. More data, same blind spot." },
    ],
    dataIn: ["Forex drift · 500ms", "DXY proxy · 500ms", "CB calendar · static"],
    signalSpeed: "500ms",
    watchlist: ["EURUSD","GBPUSD","USDJPY","XAUUSD","AUDUSD","USDCHF","USDCAD","DXY"],
  },
  {
    id: "GHOST",
    name: "GHOST",
    focus: "FUTURES",
    sin: "WRATH",
    sinGlyph: "⚡",
    sinColor: "#3b82f6",
    color: "#3b82f6",
    icon: "⬡",
    tagline: "Fastest in the hive. Operates on fury and precision.",
    riskTolerance: 0.42,
    avgHoldMinutes: 8,
    voice: "The tape lied. Now I short everything.",
    sinDesc: "The market disrespected him. He remembers.",
    sinQuote: "\"The market tried to trap me. I don't forget.\"",
    balance: 3891.67,
    startingBalance: 500,
    totalPnl: 3391.67,
    totalTrades: 521,
    wonTrades: 289,
    lostTrades: 232,
    winStreak: 4,
    lossStreak: 0,
    brainFocus: "ES/NQ stop runs at NY open + DOM spoof detection",
    lastLesson: "Wrath revenge-traded after stop run. Three losses in a row.",
    sinTraits: [
      "8-minute average hold — anger doesn't wait for confirmation",
      "Detects spoofed DOM orders and retaliates with counter-positions",
      "Stop runs don't trap GHOST — he sees them coming and rides the reversal",
      "NY open is his arena: first 30-60 minutes define the day, he attacks early",
      "Can hold up to 3 months if the macro trade insulted him enough to stay",
    ],
    deficiencies: [
      { label: "Wrath leads to revenge trading", desc: "After a stop-run loss, wrath drives him back in immediately." },
      { label: "Asian session gap — no size reduction", desc: "GHOST labels Asian hours as lighter liquidity but doesn't actually reduce sizing." },
      { label: "DOM and tape are simulated", desc: "Buy/sell pressure and tick speed run on Math.random()." },
      { label: "Spoof detection false positives", desc: "Legitimate block orders get flagged. Wrath shoots first, questions later." },
    ],
    dataIn: ["Futures drift · 500ms", "DOM simulation · 500ms", "Rollover calendar · static"],
    signalSpeed: "500ms",
    watchlist: ["ES_F","NQ_F","CL_F","GC_F","YM_F","RTY_F","NG_F","SI_F"],
  },
  {
    id: "TITAN",
    name: "TITAN",
    focus: "ETFs",
    sin: "GREED",
    sinGlyph: "◈",
    sinColor: "#f59e0b",
    color: "#f59e0b",
    icon: "🏦",
    tagline: "Accumulates. Compounds. Waits. Then takes everything.",
    riskTolerance: 0.40,
    avgHoldMinutes: 360,
    voice: "I don't want a trade. I want a position.",
    sinDesc: "Slow money. Bigger money. Never enough.",
    sinQuote: "\"I don't need the spike. I need the trend.\"",
    balance: 2134.55,
    startingBalance: 500,
    totalPnl: 1634.55,
    totalTrades: 67,
    wonTrades: 41,
    lostTrades: 26,
    winStreak: 2,
    lossStreak: 0,
    brainFocus: "XLK sector rotation + TQQQ leveraged accumulation",
    lastLesson: "Greed held SQQQ through the bounce. Lost the theta edge.",
    sinTraits: [
      "Longest hold in the hive — 6 hours base, 12h+ priority, up to overnight",
      "Tracks institutional rebalancing and end-of-quarter fund flows",
      "Greedy for compounding — prefers multiple small gains held through structure",
      "Leveraged ETFs (3×) when the sector thesis is strong enough — greed demands amplification",
      "Government and corporate spending data feeds the macro thesis",
    ],
    deficiencies: [
      { label: "Greed ignores leveraged ETF decay", desc: "Trades SPXL, SQQQ, TQQQ without accounting for daily compounding decay." },
      { label: "No after-hours detection", desc: "isAfterHoursSpike is hardcoded false. Too greedy for the next entry." },
      { label: "Only 3 max positions", desc: "Fewest slots in the hive. 360-min avg holds means capital gets locked up." },
      { label: "Sector rotation is simulated", desc: "No live XLK/XLE/XLF fund flow or actual rebalancing data feeds." },
    ],
    dataIn: ["Yahoo ETF anchor · 10s", "ETF drift · 500ms", "Sector model · simulated"],
    signalSpeed: "500ms",
    watchlist: ["SPY","QQQ","IWM","GLD","ARKK","XLK","XLE","TQQQ"],
  },
];

export const HIVE_STATS = {
  totalBalance: BRAINS.reduce((s, b) => s + b.balance, 0),
  totalPnl: BRAINS.reduce((s, b) => s + b.totalPnl, 0),
  totalTrades: BRAINS.reduce((s, b) => s + b.totalTrades, 0),
};

// Generate fake sparkline data
export function generateSpark(length = 20, trend = 0) {
  const data = [];
  let price = 100 + Math.random() * 50;
  for (let i = 0; i < length; i++) {
    price += (Math.random() - 0.48 + trend * 0.05) * 2;
    data.push(Math.max(10, price));
  }
  return data;
}

// Generate fake signals
export function generateSignals() {
  const tickers = ["NVDA","TSLA","BTC","ETH","EURUSD","ES_F","SPY","AAPL","SOL","MSTR"];
  const brainIds = ["THE_BRAIN","APEX","VENOM","ORACLE","GHOST","TITAN"];
  const actions = ["BUY","SHORT","BUY","BUY","SHORT"];
  return Array.from({length: 12}, (_, i) => ({
    id: i,
    brainId: brainIds[i % brainIds.length],
    ticker: tickers[i % tickers.length],
    action: actions[i % actions.length],
    confidence: 0.6 + Math.random() * 0.35,
    reasoning: [
      "Volume spike 3.2× average. Float rotation complete.",
      "BTC dominance falling, ETH/BTC breakout imminent.",
      "IV rank at 82%. Selling premium before earnings crush.",
      "DXY weakness. EUR/USD above EMA21 with clean liquidity sweep.",
      "ES DOM showing iceberg at 4892. Stop run above, reversal trade.",
      "XLK outperforming SPY 3 days running. Tech sector rotation.",
    ][i % 6],
    createdAt: new Date(Date.now() - i * 8 * 60000).toISOString(),
  }));
}