// 21 indicator-specific graph retrieval agents.
// Each agent is brain-aware: it knows which brains care about it most
// and renders with their watchlists + colors.

// TradingView study IDs
const RSI     = 'RSI@tv-basicstudies';
const MACD    = 'MACD@tv-basicstudies';
const VOL     = 'Volume@tv-studiess';
const VWAP    = 'VWAP@tv-basicstudies';
const BB      = 'BB@tv-basicstudies';
const STOCH   = 'Stoch@tv-basicstudies';
const ATR     = 'ATR@tv-basicstudies';
const EMA     = 'Moving Average Exponential@tv-basicstudies';
const SMA     = 'Moving Average@tv-basicstudies';
const ICHIMOKU= 'IchimokuCloud@tv-basicstudies';

// TV chart styles
export const STYLE_CANDLE  = '1';
export const STYLE_LINE    = '2';
export const STYLE_AREA    = '3';
export const STYLE_HEIKIN  = '8';

// Brain relevance tiers
const ALL   = ['THE_BRAIN','APEX','VENOM','ORACLE','GHOST','TITAN'];
const STOCK = ['THE_BRAIN','VENOM','TITAN'];
const INTRA = ['THE_BRAIN','VENOM','GHOST'];
const TECH  = ['THE_BRAIN','APEX','VENOM','GHOST'];
const MACRO = ['ORACLE','TITAN','THE_BRAIN'];

export const INDICATOR_AGENTS = {
  price: {
    id: 'price',
    label: 'LIVE PRICE',
    shortLabel: 'PRICE',
    icon: '◈',
    color: '#FFB81C',
    description: 'Real-time OHLCV price action. The foundation of every signal.',
    tvStudies: [VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: ALL,
    timeframes: ['1','5','15','60','D'],
    keySignals: [
      'Price vs VWAP (above = bullish bias)',
      'Distance from 52-week high/low',
      'Open vs prior close (gap detection)',
      'Current candle body size vs ATR',
    ],
    dataDelay: '15-min delayed (stocks/ETFs) · Near real-time (crypto/forex)',
    reliability: '9/10',
    outputFields: ['Current Price','Day Open','Day High','Day Low','After-Hours Price','Move %'],
  },

  candles: {
    id: 'candles',
    label: 'CANDLESTICK PATTERNS',
    shortLabel: 'CANDLES',
    icon: '▮',
    color: '#f59e0b',
    description: 'Candle pattern recognition: doji, hammer, engulfing, morning/evening star.',
    tvStudies: [VOL, EMA],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: ALL,
    timeframes: ['1','5','15','60','D','W'],
    keySignals: [
      'Doji at key S/R = indecision / reversal',
      'Bullish engulfing > prior red candle = demand',
      'Shooting star at resistance = rejection',
      'Hammer + high volume at support = reversal',
      'Three white soldiers = strong continuation',
    ],
    dataDelay: '15-min delayed (stocks/ETFs) · Near real-time (crypto/forex)',
    reliability: '9/10',
    outputFields: ['Pattern Detected','Candle Type','Body %','Wick Ratio','Context'],
  },

  volume: {
    id: 'volume',
    label: 'VOLUME CHART',
    shortLabel: 'VOLUME',
    icon: '▰',
    color: '#3b82f6',
    description: 'Volume bars, OBV, and cumulative delta. Confirm price moves with volume.',
    tvStudies: [VOL, RSI],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: ALL,
    timeframes: ['1','5','15','60','D'],
    keySignals: [
      'Green bar on 2×+ avg volume = strong buyers',
      'Red bar on high volume at support = capitulation',
      'Low-volume breakout = suspect — wait for confirm',
      'Volume climax near highs = distribution',
      'Relative volume >3× = news catalyst or squeeze',
    ],
    dataDelay: '15-min delayed · Real-time via broker feed',
    reliability: '9/10',
    outputFields: ['Current Volume','Avg Volume (20D)','Rel. Volume','Volume Trend','Delta'],
  },

  vwap: {
    id: 'vwap',
    label: 'VWAP',
    shortLabel: 'VWAP',
    icon: '⊛',
    color: '#22c55e',
    description: 'Volume-Weighted Average Price. Intraday institutional benchmark.',
    tvStudies: [VWAP, VOL, BB],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: INTRA,
    timeframes: ['1','5','15','60'],
    keySignals: [
      'Price reclaims VWAP on volume = long bias',
      'Price rejected at VWAP 3× = short bias',
      'Gap-and-go above VWAP at open = momentum',
      'VWAP slope rising = trending day',
      'Price pinned to VWAP = ranging / low conviction',
    ],
    dataDelay: 'Intraday only · Resets at session open',
    reliability: '9/10',
    outputFields: ['VWAP Level','Price vs VWAP','VWAP Band Upper','VWAP Band Lower','Anchored VWAP'],
  },

  ma: {
    id: 'ma',
    label: 'MOVING AVERAGES',
    shortLabel: 'MAs',
    icon: '∿',
    color: '#a855f7',
    description: 'EMA20/50/200 and SMA crossovers. Trend identification and dynamic S/R.',
    tvStudies: [EMA, EMA, SMA, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '60',
    primaryBrains: [...TECH, ...MACRO],
    timeframes: ['15','60','240','D','W'],
    keySignals: [
      'Price > EMA20 > EMA50 > EMA200 = strong uptrend',
      'Golden cross (EMA50 > EMA200) = bull signal',
      'Death cross (EMA50 < EMA200) = bear signal',
      'EMA20 bounce on pullback = trend continuation',
      'Price below all MAs = avoid longs / look for shorts',
    ],
    dataDelay: '15-min delayed (stocks/ETFs)',
    reliability: '9/10',
    outputFields: ['EMA20','EMA50','EMA200','SMA200','Trend Direction','MA Alignment'],
  },

  rsi: {
    id: 'rsi',
    label: 'RSI',
    shortLabel: 'RSI',
    icon: '◑',
    color: '#ef4444',
    description: 'Relative Strength Index (14). Overbought >70, oversold <30. Divergence signals.',
    tvStudies: [RSI, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: ALL,
    timeframes: ['1','5','15','60','D'],
    keySignals: [
      'RSI >70 = overbought — watch for rejection',
      'RSI <30 = oversold — watch for bounce',
      'Bullish divergence: price lower low, RSI higher low = reversal',
      'Bearish divergence: price higher high, RSI lower high = topping',
      'RSI 50 cross = momentum shift',
      'RSI 40 hold in uptrend = strong bull',
    ],
    dataDelay: 'Computed from delayed price data',
    reliability: '9/10',
    outputFields: ['RSI (14)','RSI Zone','Divergence','Overbought Level','Oversold Level'],
  },

  macd: {
    id: 'macd',
    label: 'MACD',
    shortLabel: 'MACD',
    icon: '≋',
    color: '#06b6d4',
    description: 'MACD (12,26,9). Momentum + trend crossover system. Histogram expansion.',
    tvStudies: [MACD, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: ALL,
    timeframes: ['5','15','60','D'],
    keySignals: [
      'MACD line crosses above signal = bullish',
      'MACD line crosses below signal = bearish',
      'Histogram growing = momentum increasing',
      'Histogram shrinking = momentum fading',
      'MACD above zero + crossover = strongest long signal',
      'Bearish divergence on daily = major top warning',
    ],
    dataDelay: 'Computed from delayed price data',
    reliability: '9/10',
    outputFields: ['MACD Line','Signal Line','Histogram','Zero Cross','Trend'],
  },

  stochastic: {
    id: 'stochastic',
    label: 'STOCHASTIC OSCILLATOR',
    shortLabel: 'STOCH',
    icon: '⟨⟩',
    color: '#ec4899',
    description: 'Stochastic %K/%D (14,3,3). Overbought/oversold with crossover signals.',
    tvStudies: [STOCH, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: TECH,
    timeframes: ['5','15','60','D'],
    keySignals: [
      '%K crosses above %D below 20 = bullish reversal',
      '%K crosses below %D above 80 = bearish reversal',
      'Double bottom in oversold zone = strong buy signal',
      'Stoch divergence from price = leading reversal warning',
      'Stoch >50 confirms uptrend momentum',
    ],
    dataDelay: 'Computed from delayed price data',
    reliability: '8/10',
    outputFields: ['%K','%D','Zone (OB/OS/Neutral)','Crossover','Divergence'],
  },

  fibonacci: {
    id: 'fibonacci',
    label: 'FIBONACCI LEVELS',
    shortLabel: 'FIB',
    icon: '⌇',
    color: '#FFB81C',
    description: 'Fib retracements (0.236, 0.382, 0.5, 0.618, 0.786) from swing high/low.',
    tvStudies: [VOL, EMA],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '60',
    primaryBrains: [...INTRA, 'ORACLE'],
    timeframes: ['15','60','240','D','W'],
    keySignals: [
      '0.382 retrace holds = shallow pullback, strong trend',
      '0.618 retrace = golden ratio, high-probability support',
      'Price bounces at 0.786 = last chance before trend reversal',
      'Fib extension 1.272 / 1.618 = momentum targets',
      'Confluence: Fib level + MA + VWAP = high-conviction zone',
    ],
    dataDelay: 'Manual drawing required · Chart link provided',
    reliability: '8/10 — Levels are user-drawn, not auto-calculated',
    outputFields: ['Swing High','Swing Low','0.382 Level','0.618 Level','1.618 Extension'],
  },

  sr: {
    id: 'sr',
    label: 'SUPPORT & RESISTANCE',
    shortLabel: 'S/R',
    icon: '⊟',
    color: '#f59e0b',
    description: 'Key horizontal S/R, trendlines, prior highs/lows, and psychological levels.',
    tvStudies: [VOL, EMA, BB],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '60',
    primaryBrains: ALL,
    timeframes: ['15','60','240','D','W'],
    keySignals: [
      'Prior day high/low = first intraday S/R',
      'Round numbers ($100, $50, $0.50) = psychological zones',
      'Trendline break + retest = high-probability entry',
      'Volume shelf at price level = institutional interest',
      '3+ touches of same level = confirmed S/R',
    ],
    dataDelay: 'Chart-derived · Manual confirmation',
    reliability: '8/10 — Structure identified visually',
    outputFields: ['Key Support','Key Resistance','Trendline','Prior Day High','Prior Day Low'],
  },

  premarket: {
    id: 'premarket',
    label: 'PRE-MARKET & AFTER-HOURS',
    shortLabel: 'PM/AH',
    icon: '◐',
    color: '#8b5cf6',
    description: 'Extended-hours session data. Gap direction, pre-market volume, catalyst check.',
    tvStudies: [VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: ['THE_BRAIN','TITAN','VENOM'],
    timeframes: ['1','5','15'],
    keySignals: [
      'PM volume >500K before open = institutional interest',
      'Gap >5% on no news = fade setup',
      'Gap >5% on earnings = gap-and-go candidate',
      'AH move >3% on results = pre-position for morning',
      'PM high = first resistance at open',
    ],
    dataDelay: 'Extended hours: available on TradingView (premarket session)',
    reliability: '7/10 — Thin liquidity; spreads wider in extended hours',
    outputFields: ['PM Price','PM Change %','PM Volume','Gap %','AH Price','AH Change %'],
  },

  intraday: {
    id: 'intraday',
    label: 'INTRADAY HIGHS & LOWS',
    shortLabel: 'HOD/LOD',
    icon: '⇅',
    color: '#22c55e',
    description: 'Session high-of-day (HOD), low-of-day (LOD), opening range, and midpoint.',
    tvStudies: [VWAP, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: INTRA,
    timeframes: ['1','5','15'],
    keySignals: [
      'Price breaks HOD on volume = continuation long',
      'Price breaks LOD = continuation short',
      'Opening range (first 5-15m) = defines session bias',
      'OR breakout + volume = trade the breakout',
      'Mid-day consolidation near HOD = flag pattern',
    ],
    dataDelay: 'Intraday data · 15-min delayed on free plan',
    reliability: '9/10',
    outputFields: ['HOD','LOD','Opening Range High','Opening Range Low','OR Midpoint','Current Vs HOD'],
  },

  gaps: {
    id: 'gaps',
    label: 'GAP-UPS & GAP-DOWNS',
    shortLabel: 'GAPS',
    icon: '⊕',
    color: '#ef4444',
    description: 'Daily gap scanner view. Gap %, fill probability, and volume confirmation.',
    tvStudies: [VOL, EMA],
    tvStyle: STYLE_CANDLE,
    defaultInterval: 'D',
    primaryBrains: ['THE_BRAIN','VENOM','TITAN'],
    timeframes: ['D','W'],
    keySignals: [
      'Gap >10% on earnings = potential multi-day mover',
      'Gap fill < 50% of gap = strong trend day',
      'Exhaustion gap: volume drying up at new high = fade',
      'Breakaway gap: occurs at key resistance on news = buy',
      'Island reversal: gap-up then gap-down = major top',
    ],
    dataDelay: 'Prior close to current open data · Daily bars',
    reliability: '9/10',
    outputFields: ['Gap Size %','Gap Direction','Prior Close','Today Open','Gap Fill %','Volume'],
  },

  relvol: {
    id: 'relvol',
    label: 'RELATIVE VOLUME',
    shortLabel: 'REL VOL',
    icon: '⊞',
    color: '#3b82f6',
    description: 'Current volume vs 20-day average at the same time of day. RVOL >2 = elevated.',
    tvStudies: [VOL, RSI],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: ['THE_BRAIN','GHOST','VENOM'],
    timeframes: ['1','5','15','60'],
    keySignals: [
      'RVOL >2× = elevated activity, institutional or news-driven',
      'RVOL >5× = potential squeeze or catalyst event',
      'RVOL <0.5× = thin market, avoid intraday trades',
      'Volume spike on green candle = distribution caution at highs',
      'RVOL rising into close = momentum continuation signal',
    ],
    dataDelay: '15-min delayed · RVOL computed against 20D avg',
    reliability: '8/10',
    outputFields: ['Current Volume','Avg Volume','RVOL Ratio','Volume Trend','Session Volume %'],
  },

  float: {
    id: 'float',
    label: 'FLOAT & MARKET CAP',
    shortLabel: 'FLOAT',
    icon: '◎',
    color: '#06b6d4',
    description: 'Public float, market cap, short interest, and shares outstanding.',
    tvStudies: [VOL, RSI],
    tvStyle: STYLE_CANDLE,
    defaultInterval: 'D',
    primaryBrains: ['THE_BRAIN','VENOM'],
    timeframes: ['D','W'],
    keySignals: [
      'Float <10M shares = extreme squeeze potential',
      'Float <50M = small-cap, high volatility',
      'Short interest >20% float = squeeze candidate',
      'Market cap <$500M = micro-cap risk/reward',
      'Locked-up shares = effective float much smaller',
    ],
    dataDelay: 'Updated daily (Finviz/Yahoo) · Not real-time',
    reliability: '7/10 — Float data lags; verify with multiple sources',
    outputFields: ['Shares Float','Market Cap','Short Interest %','Days to Cover','Shares Outstanding'],
    externalOnly: true,
  },

  options: {
    id: 'options',
    label: 'OPTIONS CHAIN',
    shortLabel: 'OPTIONS',
    icon: '⚡',
    color: '#a855f7',
    description: 'IV rank, OI by strike, put/call ratio, and max pain level.',
    tvStudies: [VOL, BB, ATR],
    tvStyle: STYLE_CANDLE,
    defaultInterval: 'D',
    primaryBrains: ['VENOM'],
    timeframes: ['D'],
    keySignals: [
      'IV rank >70% = elevated premium, favor selling',
      'IV rank <30% = cheap options, favor buying',
      'Put/call ratio >1.2 = bearish sentiment',
      'Max pain level = where options expire worthless for most buyers',
      'OI spike at specific strike = magnet for price',
    ],
    dataDelay: 'IV/OI: 15-min delayed via CBOE / Yahoo Finance options',
    reliability: '7/10 — Real options data requires broker API',
    outputFields: ['IV Rank','IV Percentile','Put/Call Ratio','Max Pain','Nearest Strike OI'],
    externalOnly: true,
  },

  sector: {
    id: 'sector',
    label: 'SECTOR COMPARISON',
    shortLabel: 'SECTOR',
    icon: '◇',
    color: '#f59e0b',
    description: 'Relative performance across sectors: XLK, XLE, XLF, XLV, XLI vs SPY.',
    tvStudies: [EMA, VOL],
    tvStyle: STYLE_LINE,
    defaultInterval: 'D',
    primaryBrains: ['TITAN','THE_BRAIN','ORACLE'],
    timeframes: ['60','D','W'],
    keySignals: [
      'XLK >SPY = tech leadership = risk-on',
      'XLE >SPY = energy leadership = inflation/macro shift',
      'XLV >SPY = defensive rotation = risk-off signal',
      'All sectors >SPY = broad market strength',
      'Single sector diverging from SPY = concentrated move',
    ],
    dataDelay: '15-min delayed ETF data',
    reliability: '9/10',
    outputFields: ['Sector Leader','Sector Laggard','SPY Performance','Rotation Signal','Risk Mode'],
    customWatchlist: [
      { symbol: 'SPY',  tv: 'AMEX:SPY',  label: 'SPY'  },
      { symbol: 'XLK',  tv: 'NYSE:XLK',  label: 'XLK'  },
      { symbol: 'XLE',  tv: 'NYSE:XLE',  label: 'XLE'  },
      { symbol: 'XLF',  tv: 'NYSE:XLF',  label: 'XLF'  },
      { symbol: 'XLV',  tv: 'NYSE:XLV',  label: 'XLV'  },
      { symbol: 'XLI',  tv: 'NYSE:XLI',  label: 'XLI'  },
      { symbol: 'XLP',  tv: 'NYSE:XLP',  label: 'XLP'  },
      { symbol: 'XLU',  tv: 'NYSE:XLU',  label: 'XLU'  },
    ],
  },

  indices: {
    id: 'indices',
    label: 'INDEX CHARTS',
    shortLabel: 'INDICES',
    icon: '▲',
    color: '#FFB81C',
    description: 'SPY, QQQ, IWM, DIA — broad market pulse and rotation signals.',
    tvStudies: [EMA, MACD, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: ['TITAN','ORACLE','THE_BRAIN'],
    timeframes: ['5','15','60','D','W'],
    keySignals: [
      'SPY and QQQ both green = risk-on, trade with trend',
      'IWM leading SPY = small-cap strength = risk appetite high',
      'DIA > QQQ = value over growth = defensive rotation',
      'All indices red at open = wait for direction',
      'SPY breaks major MA = regime change signal',
    ],
    dataDelay: '15-min delayed via TradingView (free plan)',
    reliability: '9/10',
    customWatchlist: [
      { symbol: 'SPY', tv: 'AMEX:SPY',   label: 'SPY' },
      { symbol: 'QQQ', tv: 'NASDAQ:QQQ', label: 'QQQ' },
      { symbol: 'IWM', tv: 'AMEX:IWM',   label: 'IWM' },
      { symbol: 'DIA', tv: 'AMEX:DIA',   label: 'DIA' },
    ],
    outputFields: ['SPY Level','QQQ Level','IWM Level','DIA Level','Breadth Signal'],
  },

  futures: {
    id: 'futures',
    label: 'FUTURES CHARTS',
    shortLabel: 'FUTURES',
    icon: '⬡',
    color: '#3b82f6',
    description: 'ES, NQ, YM, RTY, CL, GC front-month contracts. Pre-market market structure.',
    tvStudies: [VWAP, VOL, EMA],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '5',
    primaryBrains: ['GHOST','ORACLE'],
    timeframes: ['1','5','15','60','D'],
    keySignals: [
      'ES overnight range = defines RTH opening bias',
      'NQ/ES divergence = tech vs broad market split',
      'CL breaking out = energy inflation signal',
      'GC rally = risk-off / dollar weakness',
      'Rollover week = volume shifts to next contract',
    ],
    dataDelay: '10-min delayed (CME free) · Real-time via broker',
    reliability: '8/10',
    customWatchlist: [
      { symbol: 'ES',  tv: 'CME_MINI:ES1!', label: 'ES'  },
      { symbol: 'NQ',  tv: 'CME_MINI:NQ1!', label: 'NQ'  },
      { symbol: 'YM',  tv: 'CBOT:YM1!',     label: 'YM'  },
      { symbol: 'RTY', tv: 'CME:RTY1!',     label: 'RTY' },
      { symbol: 'CL',  tv: 'NYMEX:CL1!',    label: 'CL'  },
      { symbol: 'GC',  tv: 'COMEX:GC1!',    label: 'GC'  },
    ],
    outputFields: ['ES Level','NQ Level','CL Level','GC Level','Trend','Session Range'],
  },

  crypto: {
    id: 'crypto',
    label: 'CRYPTO CHARTS',
    shortLabel: 'CRYPTO',
    icon: '₿',
    color: '#ef4444',
    description: 'BTC, ETH, SOL and major movers. 24/7 market with funding rate context.',
    tvStudies: [RSI, MACD, VOL],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '15',
    primaryBrains: ['APEX'],
    timeframes: ['1','5','15','60','240','D'],
    keySignals: [
      'BTC dominance rising = altcoin weakness',
      'BTC dominance falling = altseason / capital rotation',
      'Funding rate >0.1% = overleveraged longs, correction risk',
      'Funding rate negative = shorts squeezable',
      'BTC > 52W high = new bull leg',
    ],
    dataDelay: 'Near real-time via Binance feed on TradingView',
    reliability: '9/10',
    customWatchlist: [
      { symbol: 'BTC',  tv: 'BINANCE:BTCUSDT',  label: 'BTC'  },
      { symbol: 'ETH',  tv: 'BINANCE:ETHUSDT',  label: 'ETH'  },
      { symbol: 'SOL',  tv: 'BINANCE:SOLUSDT',  label: 'SOL'  },
      { symbol: 'DOGE', tv: 'BINANCE:DOGEUSDT', label: 'DOGE' },
      { symbol: 'XRP',  tv: 'BINANCE:XRPUSDT',  label: 'XRP'  },
      { symbol: 'AVAX', tv: 'BINANCE:AVAXUSDT', label: 'AVAX' },
    ],
    outputFields: ['BTC Price','ETH Price','BTC Dominance','Total Market Cap','Funding Rate','Trend'],
  },

  forex: {
    id: 'forex',
    label: 'FOREX CHARTS',
    shortLabel: 'FOREX',
    icon: '💱',
    color: '#22c55e',
    description: 'EUR/USD, GBP/USD, USD/JPY and major pairs with DXY macro context.',
    tvStudies: [EMA, RSI, MACD],
    tvStyle: STYLE_CANDLE,
    defaultInterval: '60',
    primaryBrains: ['ORACLE'],
    timeframes: ['15','60','240','D','W'],
    keySignals: [
      'DXY > 104 = dollar strength, pressure on EUR/USD',
      'London open 3-8am ET = highest liquidity, true direction',
      'NY open 8am-12pm ET = peak volatility window',
      'NFP Friday = extreme volatility, widen stops',
      'ECB/FOMC divergence = trend change in EUR/USD',
    ],
    dataDelay: 'Near real-time FX feed via TradingView',
    reliability: '8/10',
    customWatchlist: [
      { symbol: 'EURUSD', tv: 'FX:EURUSD', label: 'EUR/USD' },
      { symbol: 'GBPUSD', tv: 'FX:GBPUSD', label: 'GBP/USD' },
      { symbol: 'USDJPY', tv: 'FX:USDJPY', label: 'USD/JPY' },
      { symbol: 'XAUUSD', tv: 'FX:XAUUSD', label: 'XAU/USD' },
      { symbol: 'AUDUSD', tv: 'FX:AUDUSD', label: 'AUD/USD' },
      { symbol: 'DXY',    tv: 'TVC:DXY',   label: 'DXY'     },
    ],
    outputFields: ['EUR/USD','GBP/USD','USD/JPY','DXY Level','Session','Risk Bias'],
  },
};

export const INDICATOR_LIST = Object.values(INDICATOR_AGENTS);

// Resolve a brain watchlist symbol to a TradingView symbol
export function toTVSymbol(symbol, brainFocus) {
  const cryptoMap = {
    BTC: 'BINANCE:BTCUSDT', ETH: 'BINANCE:ETHUSDT', SOL: 'BINANCE:SOLUSDT',
    DOGE: 'BINANCE:DOGEUSDT', ADA: 'BINANCE:ADAUSDT', XRP: 'BINANCE:XRPUSDT',
    AVAX: 'BINANCE:AVAXUSDT', LINK: 'BINANCE:LINKUSDT',
  };
  const forexMap = {
    EURUSD: 'FX:EURUSD', GBPUSD: 'FX:GBPUSD', USDJPY: 'FX:USDJPY',
    XAUUSD: 'FX:XAUUSD', AUDUSD: 'FX:AUDUSD', USDCHF: 'FX:USDCHF',
    USDCAD: 'FX:USDCAD', DXY: 'TVC:DXY',
  };
  const futuresMap = {
    ES_F: 'CME_MINI:ES1!', NQ_F: 'CME_MINI:NQ1!', CL_F: 'NYMEX:CL1!',
    GC_F: 'COMEX:GC1!', YM_F: 'CBOT:YM1!', RTY_F: 'CME:RTY1!',
    NG_F: 'NYMEX:NG1!', SI_F: 'COMEX:SI1!',
  };

  if (brainFocus === 'CRYPTO') return cryptoMap[symbol] || `BINANCE:${symbol}USDT`;
  if (brainFocus === 'FOREX')  return forexMap[symbol]  || `FX:${symbol}`;
  if (brainFocus === 'FUTURES') return futuresMap[symbol] || symbol;
  return symbol; // stocks and ETFs: TradingView resolves these directly
}
