// Market Graph Retrieval Agent configurations — one per asset class
// Each agent is paired with its corresponding Hive brain

export const MARKET_AGENTS = {
  stocks: {
    id: "stocks",
    path: "/market/stocks",
    name: "THE BRAIN",
    label: "STOCKS",
    icon: "📈",
    color: "#FFB81C",
    brainId: "THE_BRAIN",
    tagline: "Low-float squeezes + catalyst plays",
    assetType: "Stock",
    defaultInterval: "15",
    source: "TradingView / Yahoo Finance / NASDAQ",
    dataDelay: "15-min delayed (free plan) · Pre/AH data available",
    reliability: "9/10 — NASDAQ + Yahoo confirmed symbols",
    indicators: ["RSI", "MACD", "EMA20", "EMA50", "EMA200", "VWAP", "Volume", "Rel. Volume", "Fib Levels", "Support/Resistance"],
    timeframes: [
      { label: "1M",  value: "1"  },
      { label: "5M",  value: "5"  },
      { label: "15M", value: "15" },
      { label: "1H",  value: "60" },
      { label: "D",   value: "D"  },
      { label: "W",   value: "W"  },
    ],
    watchlist: [
      { symbol: "NVDA",  tv: "NASDAQ:NVDA",  label: "NVDA"  },
      { symbol: "TSLA",  tv: "NASDAQ:TSLA",  label: "TSLA"  },
      { symbol: "GME",   tv: "NYSE:GME",     label: "GME"   },
      { symbol: "AMC",   tv: "NYSE:AMC",     label: "AMC"   },
      { symbol: "SOUN",  tv: "NASDAQ:SOUN",  label: "SOUN"  },
      { symbol: "BBAI",  tv: "NASDAQ:BBAI",  label: "BBAI"  },
      { symbol: "MVIS",  tv: "NASDAQ:MVIS",  label: "MVIS"  },
      { symbol: "IONQ",  tv: "NYSE:IONQ",    label: "IONQ"  },
    ],
    links: {
      finviz:  (s) => `https://finviz.com/quote.ashx?t=${s}`,
      yahoo:   (s) => `https://finance.yahoo.com/quote/${s}/chart`,
      nasdaq:  (s) => `https://www.nasdaq.com/market-activity/stocks/${s.toLowerCase()}`,
      tv:      (s) => `https://www.tradingview.com/chart/?symbol=${s}`,
    },
    summary: "Monitors low-float small caps and large-cap catalyst plays. Key focus: gap-ups, squeeze setups, RSI oversold/overbought, VWAP reclaims, and relative volume spikes above 2×.",
  },

  crypto: {
    id: "crypto",
    path: "/market/crypto",
    name: "APEX",
    label: "CRYPTO",
    icon: "₿",
    color: "#ef4444",
    brainId: "APEX",
    tagline: "BTC/USDT 1-min OHLCV + LLM news sentiment",
    assetType: "Cryptocurrency",
    defaultInterval: "5",
    source: "Binance / CoinGecko / CoinMarketCap",
    dataDelay: "Near real-time via Binance feed",
    reliability: "9/10 — Binance spot data, high liquidity pairs",
    indicators: ["RSI", "MACD", "Funding Rate", "Volume", "LSTM Window (20-50 bars)", "BTC Dominance", "LLM Sentiment"],
    timeframes: [
      { label: "1M",  value: "1"   },
      { label: "5M",  value: "5"   },
      { label: "15M", value: "15"  },
      { label: "1H",  value: "60"  },
      { label: "4H",  value: "240" },
      { label: "D",   value: "D"   },
    ],
    watchlist: [
      { symbol: "BTC",  tv: "BINANCE:BTCUSDT",  label: "BTC"  },
      { symbol: "ETH",  tv: "BINANCE:ETHUSDT",  label: "ETH"  },
      { symbol: "SOL",  tv: "BINANCE:SOLUSDT",  label: "SOL"  },
      { symbol: "DOGE", tv: "BINANCE:DOGEUSDT", label: "DOGE" },
      { symbol: "ADA",  tv: "BINANCE:ADAUSDT",  label: "ADA"  },
      { symbol: "XRP",  tv: "BINANCE:XRPUSDT",  label: "XRP"  },
      { symbol: "AVAX", tv: "BINANCE:AVAXUSDT", label: "AVAX" },
      { symbol: "LINK", tv: "BINANCE:LINKUSDT", label: "LINK" },
    ],
    links: {
      coingecko:    (s) => `https://www.coingecko.com/en/coins/${s.toLowerCase()}`,
      coinmarketcap:(s) => `https://coinmarketcap.com/currencies/${s.toLowerCase()}`,
      binance:      (s) => `https://www.binance.com/en/trade/${s}_USDT`,
      tv:           (s) => `https://www.tradingview.com/chart/?symbol=BINANCE:${s}USDT`,
    },
    summary: "Tracks major crypto pairs on Binance 1-min OHLCV. APEX uses DDQN+LSTM. Key signals: funding rate spikes, BTC dominance shifts, RSI extremes, news sentiment score ≥4/5.",
  },

  options: {
    id: "options",
    path: "/market/options",
    name: "VENOM",
    label: "OPTIONS",
    icon: "⚡",
    color: "#a855f7",
    brainId: "VENOM",
    tagline: "IV crush plays + gamma scalping via GRPO",
    assetType: "Options / Underlying Equity",
    defaultInterval: "15",
    source: "TradingView / CBOE (IV proxy) / Yahoo Finance",
    dataDelay: "15-min delayed · Live IV via broker integration required",
    reliability: "7/10 — Underlying live; IV/OI data is estimated",
    indicators: ["RSI", "MACD", "Bollinger Bands", "IV Rank", "Open Interest", "Options Skew", "VWAP", "Volume", "ATR"],
    timeframes: [
      { label: "5M",  value: "5"  },
      { label: "15M", value: "15" },
      { label: "1H",  value: "60" },
      { label: "4H",  value: "240"},
      { label: "D",   value: "D"  },
    ],
    watchlist: [
      { symbol: "NVDA",  tv: "NASDAQ:NVDA",  label: "NVDA"  },
      { symbol: "TSLA",  tv: "NASDAQ:TSLA",  label: "TSLA"  },
      { symbol: "META",  tv: "NASDAQ:META",  label: "META"  },
      { symbol: "MSTR",  tv: "NASDAQ:MSTR",  label: "MSTR"  },
      { symbol: "COIN",  tv: "NASDAQ:COIN",  label: "COIN"  },
      { symbol: "AMD",   tv: "NASDAQ:AMD",   label: "AMD"   },
      { symbol: "PLTR",  tv: "NYSE:PLTR",    label: "PLTR"  },
      { symbol: "SPY",   tv: "AMEX:SPY",     label: "SPY"   },
    ],
    links: {
      cboe:    (s) => `https://www.cboe.com/delayed_quotes/${s}/options`,
      yahoo:   (s) => `https://finance.yahoo.com/quote/${s}/options`,
      barchart:(s) => `https://www.barchart.com/stocks/quotes/${s}/options`,
      tv:      (s) => `https://www.tradingview.com/chart/?symbol=${s}`,
    },
    summary: "Monitors underlying equities for options setups. VENOM targets IV crush, gamma scalps, and skew plays. Key signals: IV rank >70%, ATM skew rising, event proximity (earnings/FOMC).",
  },

  forex: {
    id: "forex",
    path: "/market/forex",
    name: "ORACLE",
    label: "FOREX",
    icon: "💱",
    color: "#22c55e",
    brainId: "ORACLE",
    tagline: "DXY divergence + LLM-guided macro strategy",
    assetType: "Foreign Exchange",
    defaultInterval: "60",
    source: "TradingView / ForexFactory / Investing.com",
    dataDelay: "Near real-time FX feed via TradingView",
    reliability: "8/10 — Major pairs; spread/execution data from broker required",
    indicators: ["RSI", "MACD", "EMA50", "EMA200", "DXY Correlation", "COT Report", "Session Overlay", "ATR", "Fib Retracements"],
    timeframes: [
      { label: "5M",  value: "5"   },
      { label: "15M", value: "15"  },
      { label: "1H",  value: "60"  },
      { label: "4H",  value: "240" },
      { label: "D",   value: "D"   },
      { label: "W",   value: "W"   },
    ],
    watchlist: [
      { symbol: "EURUSD", tv: "FX:EURUSD", label: "EUR/USD" },
      { symbol: "GBPUSD", tv: "FX:GBPUSD", label: "GBP/USD" },
      { symbol: "USDJPY", tv: "FX:USDJPY", label: "USD/JPY" },
      { symbol: "XAUUSD", tv: "FX:XAUUSD", label: "XAU/USD" },
      { symbol: "AUDUSD", tv: "FX:AUDUSD", label: "AUD/USD" },
      { symbol: "USDCHF", tv: "FX:USDCHF", label: "USD/CHF" },
      { symbol: "USDCAD", tv: "FX:USDCAD", label: "USD/CAD" },
      { symbol: "DXY",    tv: "TVC:DXY",   label: "DXY"     },
    ],
    links: {
      forexfactory: (s) => `https://www.forexfactory.com/`,
      investing:    (s) => `https://www.investing.com/currencies/${s.toLowerCase().replace('','-')}`,
      tv:           (s) => `https://www.tradingview.com/chart/?symbol=FX:${s}`,
    },
    summary: "Tracks G10 pairs with macro overlay. ORACLE uses LLM+DDQN strategy. Key signals: DXY divergence, session breaks (London/NY), FOMC/ECB/BOJ events, GDP/PMI/CPI confluence.",
  },

  futures: {
    id: "futures",
    path: "/market/futures",
    name: "GHOST",
    label: "FUTURES",
    icon: "⬡",
    color: "#3b82f6",
    brainId: "GHOST",
    tagline: "ES/NQ stop runs + PPO with band turnover reg",
    assetType: "Futures Contract",
    defaultInterval: "5",
    source: "CME Group / TradingView / Alpaca",
    dataDelay: "10-min delayed (CME free) · Real-time via broker",
    reliability: "8/10 — Exchange-grade data via CME; DOM is simulated",
    indicators: ["RSI", "MACD", "VWAP", "Volume Profile", "DOM Pressure", "Open Interest", "Rollover Calendar", "ATR", "PPO Turnover"],
    timeframes: [
      { label: "1M",  value: "1"  },
      { label: "5M",  value: "5"  },
      { label: "15M", value: "15" },
      { label: "1H",  value: "60" },
      { label: "D",   value: "D"  },
    ],
    watchlist: [
      { symbol: "ES",  tv: "CME_MINI:ES1!", label: "ES"  },
      { symbol: "NQ",  tv: "CME_MINI:NQ1!", label: "NQ"  },
      { symbol: "YM",  tv: "CBOT:YM1!",     label: "YM"  },
      { symbol: "RTY", tv: "CME:RTY1!",     label: "RTY" },
      { symbol: "CL",  tv: "NYMEX:CL1!",    label: "CL"  },
      { symbol: "GC",  tv: "COMEX:GC1!",    label: "GC"  },
      { symbol: "NG",  tv: "NYMEX:NG1!",    label: "NG"  },
      { symbol: "SI",  tv: "COMEX:SI1!",    label: "SI"  },
    ],
    links: {
      cme:  (s) => `https://www.cmegroup.com/markets/equities.html`,
      tv:   (s) => `https://www.tradingview.com/chart/?symbol=${s}`,
    },
    summary: "Monitors ES, NQ, CL, GC front-month contracts. GHOST uses PPO+TvrReg. Key signals: NY open stop runs, DOM iceberg orders, 8-min reversal setups, VWAP reclaims, rollover dates.",
  },

  etf: {
    id: "etf",
    path: "/market/etf",
    name: "TITAN",
    label: "ETFs",
    icon: "🏦",
    color: "#f59e0b",
    brainId: "TITAN",
    tagline: "S&P 500 multi-indicator A2C + XLK sector rotation",
    assetType: "Exchange-Traded Fund",
    defaultInterval: "60",
    source: "TradingView / Yahoo Finance / AMEX / NASDAQ",
    dataDelay: "15-min delayed (free) · Real-time via broker",
    reliability: "9/10 — Exchange-listed ETFs, high liquidity",
    indicators: ["RSI", "MACD", "SMA20", "EMA50", "Bollinger Bands", "Ichimoku Cloud", "SuperTrend", "ATR", "Volume", "Sector Flow"],
    timeframes: [
      { label: "15M", value: "15" },
      { label: "1H",  value: "60" },
      { label: "4H",  value: "240"},
      { label: "D",   value: "D"  },
      { label: "W",   value: "W"  },
    ],
    watchlist: [
      { symbol: "SPY",  tv: "AMEX:SPY",     label: "SPY"  },
      { symbol: "QQQ",  tv: "NASDAQ:QQQ",   label: "QQQ"  },
      { symbol: "IWM",  tv: "AMEX:IWM",     label: "IWM"  },
      { symbol: "DIA",  tv: "AMEX:DIA",     label: "DIA"  },
      { symbol: "GLD",  tv: "NYSE:GLD",     label: "GLD"  },
      { symbol: "ARKK", tv: "NYSE:ARKK",    label: "ARKK" },
      { symbol: "XLK",  tv: "NYSE:XLK",     label: "XLK"  },
      { symbol: "TQQQ", tv: "NASDAQ:TQQQ",  label: "TQQQ" },
    ],
    links: {
      yahoo:  (s) => `https://finance.yahoo.com/quote/${s}/chart`,
      etfdb:  (s) => `https://etfdb.com/etf/${s}/`,
      tv:     (s) => `https://www.tradingview.com/chart/?symbol=${s}`,
    },
    summary: "Tracks broad market + sector ETFs. TITAN uses A2C with Ichimoku + SuperTrend + Bollinger. Key signals: cloud breakouts, sector rotation (XLK vs XLE vs XLF), leveraged ETF Bollinger squeezes.",
  },

  econ: {
    id: "econ",
    path: "/market/econ",
    name: "MACRO LENS",
    label: "ECON",
    icon: "◎",
    color: "#06b6d4",
    brainId: null,
    tagline: "VIX · DXY · Yields · Oil · Gold · Fed Rates",
    assetType: "Economic Indicator / Macro",
    defaultInterval: "D",
    source: "TradingView / FRED / CME / Investing.com",
    dataDelay: "FRED data: end-of-day · Market proxies: 15-min delayed",
    reliability: "8/10 — Official gov/exchange data; some series lag by release schedule",
    indicators: ["Trend", "52W High/Low", "Rate of Change", "YoY Change", "Moving Averages", "Correlation Matrix"],
    timeframes: [
      { label: "D",  value: "D"  },
      { label: "W",  value: "W"  },
      { label: "M",  value: "M"  },
    ],
    watchlist: [
      { symbol: "VIX",    tv: "TVC:VIX",     label: "VIX"    },
      { symbol: "DXY",    tv: "TVC:DXY",     label: "DXY"    },
      { symbol: "US10Y",  tv: "TVC:US10Y",   label: "10Y"    },
      { symbol: "US02Y",  tv: "TVC:US02Y",   label: "2Y"     },
      { symbol: "GOLD",   tv: "TVC:GOLD",    label: "GOLD"   },
      { symbol: "USOIL",  tv: "TVC:USOIL",   label: "OIL"    },
      { symbol: "NATGAS", tv: "TVC:NATGAS",  label: "NATGAS" },
      { symbol: "SPX",    tv: "SP:SPX",      label: "SPX"    },
    ],
    links: {
      fred:       (s) => `https://fred.stlouisfed.org/`,
      investing:  (s) => `https://www.investing.com/economic-calendar/`,
      tv:         (s) => `https://www.tradingview.com/chart/?symbol=${s}`,
    },
    summary: "Macro dashboard: VIX fear gauge, DXY dollar strength, yield curve (2Y/10Y spread), commodities. Key signals: VIX >30 = fear spike, inverted yield curve, DXY breakouts, gold/oil correlation shifts.",
  },
};

export const AGENT_LIST = Object.values(MARKET_AGENTS);
